#!/data/data/com.termux/files/usr/bin/bash

CODE_DIR="$HOME/code_assistant"
LOG_FILE="$HOME/mistr_mintr.log"
GIT_DIR="$HOME/devsvaultspro"

mkdir -p "$CODE_DIR"

echo "🤖 CodeMate MAX is online. Type 'exit' to quit."

while true; do
  echo -n "🧠 Enter coding instruction: "
  read -r INPUT

  # Exit condition
  if [[ "$INPUT" == "exit" ]]; then
    echo "👋 Exiting CodeMate."
    break
  fi

  # Logging to Mistr Mintr
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $INPUT" >> "$LOG_FILE"

  # Generating file from instruction (simplified logic)
  FILENAME="$CODE_DIR/script_$(date +%s).sh"
  echo "#!/bin/bash" > "$FILENAME"
  echo "# Code generated by CodeMate" >> "$FILENAME"
  echo "# Instruction: $INPUT" >> "$FILENAME"
  echo "" >> "$FILENAME"
  echo "$INPUT" >> "$FILENAME"
  chmod +x "$FILENAME"

  echo "✅ Saved to $FILENAME"

  # Run code
  echo "🚀 Running script output:"
  "$FILENAME"

  # Git commit (if git repo is found)
  if [ -d "$GIT_DIR/.git" ]; then
    cp "$FILENAME" "$GIT_DIR/"
    cd "$GIT_DIR" || continue
    git add .
    git commit -m "🤖 Auto-commit by CodeMate: $(date '+%Y-%m-%d %H:%M:%S')"
    cd "$HOME" || continue
    echo "📦 Code committed to Git."
  else
    echo "⚠️ Git repo not found in $GIT_DIR."
  fi
done
